{% set name = "language_tool_python" %}
{% set version = "2.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jxmorris12/{{ name }}/archive/{{ version }}.tar.gz
  sha256: d387f36b9777f7417b58e6b32b782c330e9c0659170110c9548b569f29e8d3ec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - requests
    - tqdm
    - python

test:
  imports:
    - language_tool_python

about:
  home: https://github.com/jxmorris12/language_tool_python
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: a grammar checker for Python
  doc_url: https://pypi.org/project/language-tool-python/
  dev_url: https://github.com/jxmorris12/language_tool_python

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
